### ISSUE TITLE
Controllo sull'output

### ISSUE THREAD

**Issue by NicoloParmiggiani** [Leofaber/EllipseMatching#1]
Lanciando il comando con questi due ellissi 
3 263.493 -2.72161 0.353247 0.310958 -41.5294
S21 263.486 -2.70048 1 1 0

l’output è il seguente:
[00001] 3

ma non dovrebbe esserci anche una seconda riga come la seguente dove viene specificato se gli ellissi si intersecano o no? 
[00001] S29 overlap with [00001] S31--3

Devo confrontare tantissimi ellissi due per volta, se ci fosse questa seconda riga sarebbe facile leggere l’id in fondo per capire subito il risultato

**Comment by Leofaber** [comment]
La classe InputReader non leggeva l'ellisse dal secondo file.
